const skills={
    'Programming Languages': [
        {
            name:'C/C++',
            percent:80,
        },
        {
            name:'Javascript',
            percent:75,
        },
        {
            name:'Python',
            percent:65,
        },
        {
            name:'Java',
            percent:60,
        }
    ],
    'Web Development':[
        {
            name:'React',
            percent:75,
        },
        {
            name:'Express',
            percent:80,
        },
        {
            name:'Nodejs',
            percent:80,
        },
        {
            name:'Backend',
            percent:90,
        }
    ],
    'Databases':[
        {
            name:'MongoDB',
            percent:70,
        },
        {
            name:'SQL',
            percent:80,
        },
    ],
    'CourseWork':[
        {
            name:'Data Structure',
            percent:90,
        },
        {
            name:'Algorithm',
            percent:85,
        },
        {
            name:'OOP',
            percent:90,
        },
        {
            name:'Operating Systems',
            percent:80,
        },
        {
            name:'Computer Networks',
            percent:85,
        },
        {
            name:'DBMS',
            percent:80,
        }
    ],
    'Tools':[
        {
            name:'Git/GitHub',
            percent:70,
        },
        {
            name:'Linux',
            percent:75,
        },
        {
            name:'Socket.io',
            percent:80,
        }
    ]
};

export default skills;